<?php /* @var $meetings \Application\Collection\MeetingCollection */ ?>
<h1>Meeting</h1>


    <?php foreach ($meetings as $meeting) : /* @var $meetings \Application\Entity\Meeting */ ?>
        <ul>
            <li>Titre : <?= $meeting->titre() ?></li>
            <li>Description : <?= $meeting->description() ?></li>
            <li>Debut : <?= $meeting->endDate() ?></li>
            <li>Fin : <?= $meeting->startDate() ?></li>
        </ul>
    <?php endforeach ?>
