<?php /* @var $users \Application\Collection\MeetingCollection */ ?>


    <h2>Organiser</h2>

<?php foreach ($data as $organiser) : /* @var $meetings \Application\Entity\Meeting */ ?>
    <ul>
        <h1>Organiser : <?= $organiser[0]->name() ?></h1>
        <li>Titre : <?= $organiser[1]->titre() ?></li>
        <li>Description : <?= $organiser[1]->description() ?></li>
        <li>Debut : <?= $organiser[1]->endDate() ?></li>
        <li>Fin : <?= $organiser[1]->startDate() ?></li>

    </ul>
<?php endforeach ?>