<?php /* @var $users \Application\Collection\MeetingCollection */ ?>
    <h1>User : <?= $data[0]->name() ?></h1>

    <h2>Meetings</h2>

    <?php foreach ($data[1] as $meeting) : /* @var $meetings \Application\Entity\Meeting */ ?>
        <ul>
            <li>Community : <?= $meeting[1]->getName() ?></li>
            <li>Titre : <?= $meeting[0]->titre() ?></li>
            <li>Description : <?= $meeting[0]->description() ?></li>
            <li>Debut : <?= $meeting[0]->endDate() ?></li>
            <li>Fin : <?= $meeting[0]->startDate() ?></li>

        </ul>
    <?php endforeach ?>